const suggestionItem = [
  {
    id: 10,
    name: "Adidas NMD",
    imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
    brand: "Nike",
    price: 2500,
    soldBy: "Seller Best",
    discount: 50,
    deliveryDate: "5 Jul 2021",
    size: "M",
    qty: 1,
    orgPrice: 5000,
  },
  {
    id: 11,
    name: "Adidas Yeezy",
    imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
    brand: "Nike",
    price: 2500,
    soldBy: "Seller Best",
    discount: 50,
    deliveryDate: "5 Jul 2021",
    size: "M",
    qty: 1,
    orgPrice: 5000,
  },
  {
    id: 12,
    name: "Black Converse",
    imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
    brand: "Nike",
    price: 2500,
    soldBy: "Seller Best",
    discount: 50,
    deliveryDate: "5 Jul 2021",
    size: "M",
    qty: 1,
    orgPrice: 5000,
  },
  {
    id: 13,
    name: "Nike White AirForce",
    imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
    brand: "Nike",
    price: 2500,
    soldBy: "Seller Best",
    discount: 50,
    deliveryDate: "5 Jul 2021",
    size: "M",
    qty: 1,
    orgPrice: 5000,
  },
  {
    id: 14,
    name: "Nike Red High Tops",
    imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
    brand: "Nike",
    price: 2500,
    soldBy: "Seller Best",
    discount: 50,
    deliveryDate: "5 Jul 2021",
    size: "M",
    qty: 1,
    orgPrice: 5000,
  },
  {
    id: 15,
    name: "Nike Brown High Tops",
    imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
    brand: "Nike",
    price: 2500,
    soldBy: "Seller Best",
    discount: 50,
    deliveryDate: "5 Jul 2021",
    size: "M",
    qty: 1,
    orgPrice: 5000,
  },
  {
    id: 16,
    name: "Air Jordan Limited",
    imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
    brand: "Nike",
    price: 2500,
    soldBy: "Seller Best",
    discount: 50,
    deliveryDate: "5 Jul 2021",
    size: "M",
    qty: 1,
    orgPrice: 5000,
  },
  {
    id: 17,
    name: "Timberlands",
    imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
    brand: "Nike",
    price: 2500,
    soldBy: "Seller Best",
    discount: 50,
    deliveryDate: "5 Jul 2021",
    size: "M",
    qty: 1,
    orgPrice: 5000,
  },
];

export default suggestionItem;
